# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20160329_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.Category'),
            preserve_default=False,
        ),
    ]
