# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sale', 'For Sale'), ('onstock', 'On Stock'), ('notavailbl', 'Not Available')], default='available', max_length=10),
        ),
    ]
