# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 11:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import pages.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('creation_date', models.DateTimeField(default=pages.utils.get_now, editable=False, verbose_name='creation date')),
                ('publication_date', models.DateTimeField(blank=True, help_text='When the page should go\n            live. Status must be "Published" for page to go live.', null=True, verbose_name='publication date')),
                ('publication_end_date', models.DateTimeField(blank=True, help_text='When to expire the page.\n            Leave empty to never expire.', null=True, verbose_name='publication end date')),
                ('last_modification_date', models.DateTimeField(verbose_name='last modification date')),
                ('status', models.IntegerField(choices=[(1, 'Published'), (3, 'Hidden'), (0, 'Draft')], default=0, verbose_name='status')),
                ('template', models.CharField(blank=True, max_length=100, null=True, verbose_name='template')),
                ('delegate_to', models.CharField(blank=True, max_length=100, null=True, verbose_name='delegate to')),
                ('freeze_date', models.DateTimeField(blank=True, help_text="Don't publish any content\n            after this date.", null=True, verbose_name='freeze date')),
                ('redirect_to_url', models.CharField(blank=True, max_length=200, null=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pages.Page', verbose_name='parent')),
                ('redirect_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redirected_pages', to='pages.Page')),
            ],
            options={
                'get_latest_by': 'publication_date',
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
                'ordering': ['tree_id', 'lft'],
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
