# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pages.utils


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=5, verbose_name='language')),
                ('type', models.CharField(db_index=True, max_length=100, verbose_name='type')),
                ('body', models.TextField(verbose_name='Post content')),
                ('creation_date', models.DateTimeField(default=pages.utils.get_now, editable=False, verbose_name='creation date')),
                ('comments', models.BooleanField(verbose_name='Enable comments')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page', verbose_name='Page')),
            ],
            options={
                'get_latest_by': 'creation_date',
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
            },
        ),
    ]
