# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 15:15
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20160502_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=150, unique=True, verbose_name='Language')),
                ('country_code', models.CharField(help_text='(US, UK, CZ, SK, ...)', max_length=3, unique=True, verbose_name='Country code')),
                ('flag', models.ImageField(blank=True, help_text='Flag image to display on page.', storage=django.core.files.storage.FileSystemStorage('/home/janus/github/tdd-django/mysite/media/'), upload_to='languages', verbose_name='Flag')),
                ('default', models.BooleanField(help_text='Display as default language?', verbose_name='Default')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name_plural': 'Languages',
                'verbose_name': 'Language',
            },
        ),
        migrations.AlterModelManagers(
            name='page',
            managers=[
            ],
        ),
    ]
