# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20160502_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of meta tag &lt;meta name="THIS NAME" ... &gt;', max_length=200, verbose_name='Name')),
                ('content', models.TextField(help_text='Content of meta tag &lt;meta ... content="THIS CONTENT" &gt;', max_length=2000, verbose_name='Content')),
            ],
            options={
                'verbose_name_plural': 'Meta data',
                'verbose_name': 'Meta data',
            },
        ),
        migrations.CreateModel(
            name='MetaSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of meta set (for identification).', max_length=200, verbose_name='Name')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Language', verbose_name='Language')),
            ],
            options={
                'verbose_name_plural': 'Meta sets',
                'verbose_name': 'Meta set',
            },
        ),
        migrations.AlterModelManagers(
            name='page',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='content',
            name='language',
        ),
        migrations.AddField(
            model_name='metadata',
            name='meta_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.MetaSet', verbose_name='Meta set'),
        ),
    ]
