# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20160503_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='metadata_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.MetaSet', verbose_name='Meta set'),
        ),
    ]
