# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_page_metadata_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='For identification only', max_length=200, verbose_name='Menu name')),
            ],
            options={
                'verbose_name_plural': 'Menu',
                'verbose_name': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuitem_name', models.CharField(max_length=200, verbose_name='Menu item name')),
                ('url', models.CharField(help_text='It is recommended to write urls in SEO format, e.g.: this_is_my_site_describing_something.', max_length=200, verbose_name='Url')),
                ('position', models.IntegerField(blank=True, verbose_name='Position')),
                ('style', models.CharField(blank=True, help_text='Custom style for this menu item', max_length=200, verbose_name='Style')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Language', verbose_name='Language')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Menu', verbose_name='Menu')),
            ],
            options={
                'verbose_name_plural': 'Menu items',
                'verbose_name': 'Menu item',
            },
        ),
    ]
