# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_menu_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(max_length=200, verbose_name='Template name')),
                ('submenu_max_characters', models.PositiveIntegerField(default=150, verbose_name='Max characters in submenu')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'verbose_name_plural': 'Templates',
                'verbose_name': 'Template',
            },
        ),
    ]
