# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Script identification', max_length=50, verbose_name='Name')),
                ('code', models.TextField(help_text='Source code for script to be inserted, including &lt;script&gt;&lt;/script&gt; tags', max_length=1000, verbose_name='Code')),
            ],
            options={
                'verbose_name_plural': 'Scripts',
                'verbose_name': 'Script',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=150, verbose_name='Domain')),
                ('display_name', models.CharField(max_length=200, verbose_name='Website name')),
                ('tagline', models.CharField(blank=True, help_text='Smaller text next to website name', max_length=200, verbose_name='Tagline')),
                ('footer', models.TextField(blank=True, help_text='Custom footer with HTML to be displayed on each page', max_length=1000, verbose_name='Footer')),
            ],
            options={
                'verbose_name_plural': 'Sites',
                'verbose_name': 'Site',
            },
        ),
    ]
