# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_script_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='index',
            field=models.BooleanField(default=0, help_text='This page will be landing page for language specified for link (menu item)', verbose_name='Index page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='link',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='pages.MenuItem', verbose_name='Link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='page_content',
            field=models.TextField(blank=True, verbose_name='Page content'),
        ),
    ]
