# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20160517_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='index',
            field=models.BooleanField(default=False, help_text='This page will be landing page for language specified for link (menu item)', verbose_name='Index page'),
        ),
    ]
