# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20160517_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='content',
            name='title',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='Post title'),
            preserve_default=False,
        ),
    ]
